application: my-mapper-prod
version: 1
runtime: go
api_version: go1

handlers:
- url: /(googlefb45b81ec251a757\.html)$
  static_files: static/\1
  upload: static/.*
- url: /$
  static_files: static/index.html
  upload: static/.*
- url: /
  static_dir: static
