application: my-mapper-prod
version: 2
runtime: go
api_version: go1

handlers:
- url: /$
  static_files: dist/index.html
  upload: dist/.*
  secure: always
- url: /
  static_dir: dist
  secure: always
